---
title: "Viva_Personas"
author: "Datalords"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: yes
    toc_float: yes
    theme: journal
    highlight: pygments
    css: estilos.css
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warnings = FALSE, message = FALSE)
```

# Librerias 
```{r}
library(dplyr)
library(ggplot2)
library(dplyr)
library(readxl)
library(tidyr)
library(lubridate)
library(purrr)
library(plotly)
library(forecast)
library(readxl)
library(DataExplorer)
library(dplyr)
library(ggplot2)
library(tm)
library(wordcloud)
library(cluster)
library(factoextra) 
library(gridExtra)
library(purrr)
library(pROC)
library(rpart)
library(rpart.plot)
library(e1071)
library(ggpubr)
library(dlookr)
library(zoo)
library(caret)
library(stats)
library(tseries)
library(readr)
library(vars)
library(syuzhet)
library(kableExtra)
library(plotly)
library(scales)
library(readxl)
library(car)
library(Metrics)
library(randomForest)
```

# Preparación de datos
```{r}
summary(vuelos_alt)
vuelos_alt$ruta = as.factor(vuelos_alt$ruta)

vuelos_alt <- vuelos_alt %>%
  mutate(
    STD_hora = hour(hms(STD_hora)) * 60 + minute(hms(STD_hora))
)
```

## Cross-Validation
```{r}
set.seed(123) 
partition <- createDataPartition(y = vuelos_alt$Passengers, p=0.8, list=F)
V_train = vuelos_alt[partition, ]
V_test  = vuelos_alt[-partition, ]
```

#Modelos
## OLS1
```{r}
ols_model = lm(Passengers ~ Destination_Type + DepartureStation + STD_hora + diferencia_horas + STD_Mes + Capacity + Porcentaje_Reservas + STD_DiaSemana + STD_Dia_del_mes, data = V_train)
summary(ols_model)

pred_ols_model = predict(ols_model, newdata = V_test)
RMSE_ols_model = rmse(V_train$Passengers, pred_ols_model)
RMSE_ols_model
```

## OLS2
```{r}
ols_model2 = lm(Passengers ~ ruta+ STD_hora + diferencia_horas + STD_Mes + Capacity + Porcentaje_Reservas + STD_DiaSemana, data = V_train)
summary(ols_model2)

pred_ols_model2 = predict(ols_model2, newdata = V_test)
RMSE_ols_model2 = rmse(V_train$Passengers, pred_ols_model2)
RMSE_ols_model2
```

```{r}
vif(ols_model)
bptest(ols_model)
```

```{r}
# Ajustar el modelo de Random Forest
modelo_rf <- randomForest(Passengers ~ Destination_Type + STD_hora + diferencia_horas + STD_Mes + Capacity + Porcentaje_Reservas + STD_DiaSemana + STD_Dia_del_mes, 
                          data = V_train, 
                          ntree = 10, # Número de árboles en el bosque
                          mtry = sqrt(ncol(V_train) - 1), # Número de variables en cada división
                          importance = TRUE) # Calcular la importancia de las variables
```




