---
title: "Viva"
author: "Datalords"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: yes
    toc_float: yes
    theme: journal
    highlight: pygments
    css: estilos.css
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```

# Librerias
```{r}
library(dplyr)
library(ggplot2)
library(dplyr)
library(readxl)
library(tidyr)
library(lubridate)
library(purrr)
library(plotly)
library(forecast)
library(readxl)
library(DataExplorer)
library(dplyr)
library(ggplot2)
library(tm)
library(wordcloud)
library(cluster)
library(factoextra) 
library(gridExtra)
library(purrr)
library(pROC)
library(rpart)
library(rpart.plot)
library(e1071)
library(ggpubr)
library(dlookr)
library(zoo)
library(caret)
library(stats)
library(tseries)
library(readr)
library(vars)
library(syuzhet)
library(kableExtra)
library(plotly)
library(scales)
library(readxl)
library(lubridate)
```



# Limpieza de datos

```{r}
ventas = read.csv("databases/Sales Tec_Valid.csv")
vuelos = read.csv("databases/Filghts Tec_Valid.csv")
```

## Vuelos
```{r}
#head(vuelos)
#summary(vuelos)
```

### Tipo de dato
```{r}
vuelos$Origin_Type = as.factor(vuelos$Origin_Type)
vuelos$Destination_Type = as.factor(vuelos$Destination_Type)
#Ver si eliminar el registro ""
```

### Variables Dia/Fecha
```{r}
### Salidas
vuelos$STD <- as.POSIXct(vuelos$STD, format = "%Y-%m-%d %H:%M:%S", na.rm = TRUE)
vuelos$STD_fecha <- as.Date(vuelos$STD)
vuelos$STD_hora <- format(vuelos$STD, "%H:%M:%S")

vuelos$STA <- as.POSIXct(vuelos$STA, format = "%Y-%m-%d %H:%M:%S", na.rm = TRUE)
vuelos$STA_fecha <- as.Date(vuelos$STA)
vuelos$STA_hora <- format(vuelos$STA, "%H:%M:%S")

vuelos$diferencia_horas <- as.numeric(difftime(vuelos$STA, vuelos$STD, units = "hours"))
vuelos$diferencia_minutos <- vuelos$diferencia_horas * 60

vuelos$STD_Dia_del_mes <- day(vuelos$STD_fecha)
vuelos$STD_Mes <- month(vuelos$STD_fecha, label = TRUE)
vuelos$STD_Año <- year(vuelos$STD_fecha)

vuelos$STA_Dia_del_mes <- day(vuelos$STA_fecha)
vuelos$STA_Mes <- month(vuelos$STA_fecha, label = TRUE)
vuelos$STA_Año <- year(vuelos$STA_fecha)
```

### Porcentajes
```{r}
vuelos$Passengers <- ifelse(vuelos$Passengers > vuelos$Capacity, vuelos$Capacity, vuelos$Passengers)

vuelos <- vuelos %>%
  mutate(Porcentaje_Capacidad = (Passengers / Capacity) * 100,
         Porcentaje_Reservas = (Bookings/Capacity)*100)
```

```{r}
vuelos_alt <- vuelos %>%
  filter(STD_Año != 2024)%>%
  filter(diferencia_horas < 15)%>%
  filter(DepartureStation != "")%>%
  filter(ArrivalStation != "")%>%
  filter(Origin_Type != "")%>%
  filter(Destination_Type != "")
```

```{r}
vuelos_alt <- vuelos_alt %>%
  dplyr::select(-Aeronave)
```

```{r}
vuelos_alt$ruta <- paste(vuelos_alt$DepartureStation, vuelos_alt$ArrivalStation)
```


## Ventas 

### Corrección ProductType
#### Unicos para ProductType y ProductName
```{r}
# Obtener valores únicos para las columnas ProductType y ProductName
unicos_ProductType <- unique(ventas$ProductType)
unicos_ProductName <- unique(ventas$ProductName)
```

```{r}
# Crear un vector con los valores corregidos
valores_corregidos <- c("Botanas", "Licores", "Vivabus", "Transportaciones CUN", "Galletas",
                        "Specials", "Bebidas Calientes", "Combos Crew", "Hertz", "Ofertas",
                        "Transportaciones MTY", "Transportaciones TLC", "Viva Play", "Viva Taxis",
                        "Antros", "Viva Transfer", "Alimentos Charter", "Perecederos", "Refrescos",
                        "Sopas", "Lacteos")

# Reemplazar los valores en el conjunto de datos
ventas$ProductType <- factor(ventas$ProductType, levels = unicos_ProductType, labels = valores_corregidos)

# Verificar que los valores se hayan reemplazado correctamente
print("Valores únicos corregidos para ProductType:")
print(unique(ventas$ProductType))
```

### Corrección ProductName
```{r}
# Crear un vector con los valores corregidos sin acentos
valores_corregidos <- c("Carne Seca Habanero",
                        "Jw Red Label",
                        "Jack And Coke",
                        "Jw Red Label",
                        "Vivabus Gdl.-Nvo. C. Camionera",
                        "Ron Bacardi",
                        "Baileys",
                        "Corajillo",
                        "Transfer Cun: Zona Hotelera Sencillo",
                        "Muffin Integral",
                        "Tequila 7 Leguas Reposado",
                        "Arandano Mango Mix",
                        "Quaker Granola",
                        "Tequila 7 Leguas Blanco",
                        "Combo Cheve + Carne",
                        "Sol Clamato",
                        "Tequila + Mezclador",
                        "Quaker Avena Frutos Rojos",
                        "Go Nuts",
                        "Arandano",
                        "Combo Vino",
                        "Tinto",
                        "Nutty Berry Mix",
                        "Promo Amstel",
                        "Frutos Secos Enchilados",
                        "Vivabus Cancun: Playa Del Carmen (Sencillo)",
                        "Te Relax",
                        "Dip De Queso",
                        "Crea Combo Crew 1",
                        "Te Frutos Rojos",
                        "Ultra Seltzer Frambuesa",
                        "Corajillo Baileys",
                        "Vivabus Monterrey: Central",
                        "Vino Tinto Cria Cuervos",
                        "Cat.C.Com",
                        "Capitan Morning Con Pan Dulce",
                        "Te Manzanilla Jengibre",
                        "Apto Cun-Centro/Hoteles/Pto Juarez 1 A 6 Redondo",
                        "Baileys",
                        "Vivabus:Shuttle Apto.-Centro Tul.(Sencillo)",
                        "Nueces De Arbol Mix",
                        "Carne Seca Original",
                        "Luxury Nut Mix",
                        "Combo Cheve Doble",
                        "Botana Sabritas Con Dip De Queso",
                        "Galleta De Chispas De Chocolate",
                        "Vivabus Monterrey: Fierro (Y Griega)",
                        "Tostitos Nachos Con Dip",
                        "Promo Hsbc 1 Bebida Gratis",
                        "Protein Adventure",
                        "Crea Combo Crew 3",
                        "Vino Blanco Cria Cuervos",
                        "Hsbc-Viva",
                        "Galleta De Chocolate",
                        "Topochico Seltzer Fresa-Guayaba",
                        "Apto Cun-Centro/Hoteles/Pto Juarez 7 A 12 Redondo",
                        "Te Vainilla",
                        "Apto Cun-Centro/Hoteles/Pto Juarez 1 A 6 Sencillo",
                        "Zona-5 Sanpedro 4pax",
                        "Tulum Redondo 6 Pax",
                        "Combo Snack + Hsbc-Viva",
                        "Transfer Tlc: Aeropuerto A Observatorio",
                        "Cafe De Olla",
                        "Zona-3 Centro Mty 4pax",
                        "Cat.L.",
                        "Vivaplay",
                        "Hoteles Pdc. Playa Car. Costa Mujeres O Playa Mujeres-Priv-Sencillo",
                        "Galleta De Arandano Relleno De Q/Crema",
                        "Vivabus Cancun: Playa Del Carmen (Redondo)",
                        "Salsa Botanera",
                        "Cat.A.Subc",
                        "Cat.D.Sdn",
                        "Coco Bongo Playa",
                        "Zona-4 Tec-Mty 4pax",
                        "Taxi Cdmx - Santa Fe",
                        "Hoteles Pdc. Playa Car. Costa Mujeres O Playa Mujeres Priv-Redondo 6",
                        "Aifa A Central Taxquena",
                        "Zona-2 San Nicolas 4pax",
                        "Transfer Leon: Central.Puerta Milenio Mega Centro.Poliforum",
                        "Hsbc Promo 1c",
                        "Apto Cun Puerto-Morelos-Sencillo 1 A 6  Paxs",
                        "Apto Cun Puerto-Morelos-Sencillo 7 A 12",
                        "Cafe 19 Cafe Clasico",
                        "Hoteles Pdc. Playa Car. Costa Mujeres O Playa Mujerespriv-Sencillo 1",
                        "Zona-1 Apodaca 4pax",
                        "Apto.Gdl.-Terminal Zapopan",
                        "Guanajuato :Bjx A Central De Autobuses",
                        "Coco Bongo Cancun Apartado",
                        "Crea Combo Crew 2",
                        "Coco Bongo Full Pack",
                        "Aifa  A Central Del Norte",
                        "Transfer Tlc: Tollocan A Aicm",
                        "Tulum Sencillo 6 Pax",
                        "Zona-2 San Nicolas 10pax",
                        "Apto Cun Puerto-Morelos-Redondo7 A 12",
                        "Combo Cheve + Hsbc-Viva",
                        "Apto Cun-Centro/Hoteles/Pto Juarez 12paxs Sencillo",
                        "Charter Cheve Doble",
                        "Taxi Tlc: Centro",
                        "Cancun Plaza Las Americas Sencillo",
                        "Tulum Redondo 12 Pax",
                        "Apto Cun Puerto-Morelos-Redondo 1 A 6  Paxs",
                        "Transfer Tlc: Tollocan A Santa Fe",
                        "Silao:Bjx A Central De Autobuses",
                        "Transfer Tlc: Aeropuerto A Tollocan",
                        "Hoteles Pdc. Playa Car. Costa Mujeres O Playa Mujeres Priv-Redondo 1",
                        "Taxi Acapulco Zona Dorada 3 Pax",
                        "Combovivaplay2",
                        "Licor Charter",
                        "Quaker Avena Moras",
                        "Combo Vino Cria Cuervos",
                        "Taxi Cdmx A Polanco-Angel Independencia.",
                        "Quaker Natural Balance",
                        "San Miguel De Allende:Bjx A Central De Autobuses",
                        "Zona-6 Sancatarina 4pax",
                        "Akumal O Puerto Aventuras Sencillo 12 Pax",
                        "Akumal O Puerto Aventura Sencillo 6 Pax",
                        "Taxi Tlc: Robles. Ocoyoacac",
                        "Transfer Cjs: Centro De El Paso",
                        "Cuerno Individual Charter",
                        "Combo Stl",
                        "Eco Holder",
                        "Akumal O Puerto Aventuras Redondo 6 Pax",
                        "Taxi Cdmx - Aeropuerto",
                        "Zona-4 Tec-Mty 10pax",
                        "Transfer Tlc: Aeropuerto A Cuautitlan",
                        "Zona-5 Sanpedro 10pax",
                        "Transfer Cjs : Aeropuerto De El Paso",
                        "Taxi Veracruz-Boca Rio-6pax",
                        "Taxi Veracruz-Boca Rio-4pax",
                        "Zona-1 Apodaca 10pax",
                        "Cerveza Charter",
                        "Maxi Combo",
                        "Zona-3 Centro Mty 10pax",
                        "Taxi Cdmx - Sur. Norte",
                        "Akumal O Puerto Aventuras Redondo 12 Pax",
                        "Taxi Huatulco Puerto Escondido 3pax",
                        "Charter Licor Doble",
                        "Chokis",
                        "Sprite",
                        "Cheetos",
                        "Arcoiris",
                        "Tostitos",
                        "Xx Lager",
                        "Xx Ultra",
                        "Cafe Costa",
                        "Nissin Res",
                        "Combo Cheve",
                        "Combo Snack",
                        "Hazme Doble",
                        "Rancheritos",
                        "Super Combo",
                        "Amstel Ultra",
                        "Nissin Fuego",
                        "Tecate Light",
                        "Doritos Nacho",
                        "Jugo De Mango",
                        "Mafer Sin Sal",
                        "Ruffles Queso",
                        "Sidral Mundet",
                        "Combo Aventura",
                        "Nissin Picante",
                        "Panini Clasico",
                        "Cafe 19 Chiapas",
                        "Capitan Morning",
                        "Coca Cola Dieta",
                        "Coca Sin Azucar",
                        "Heineken Silver",
                        "Jugo De Manzana",
                        "Panini Integral",
                        "Fanta De Naranja",
                        "Licor + Refresco",
                        "Nishikawa Salado",
                        "Cafe 19 Capuchino",
                        "Ciel Mineralizada",
                        "Coca Cola Regular",
                        "Heineken Original",
                        "Combocine1",
                        "Combovivaplay3",
                        "Nissin Limon Y Habanero",
                        "Heineken 0",
                        "Taxi Tlc: Sendero",
                        "Taxi Tlc: Central. San Mateo",
                        "Taxi Zihuatanejo Zona 1-3pax",
                        "Combo Cheve Doble + Carne",
                        "Transfer Cjs: Consulado Americano",
                        "Tulum Sencillo 12 Pax",
                        "Taxi Cabos Zona 3 4pax",
                        "Zona-6 Sancatarina 10pax",
                        "Taxi Cabos Zona 1 4pax",
                        "Taxi Cdmx - Observatorio",
                        "Gomita Enchilada La Cueva",
                        "Mega Cuerno Tripulacion",
                        "Club Sandwich",
                        "Taxi Cdmx - Centro.",
                        "Combo Licor Charter",
                        "Cheve+Carne+Hsbc",
                        "Taxi Cabos Zona 2 4pax",
                        "Kacang Flaming Hot",
                        "Taxi Tlc: Zona Industial",
                        "Combo Healthy Crew",
                        "Leche De Fresa Sc",
                        "Nishikawa Japones",
                        "Super Combo Doble",
                        "Cheetos Flamin Hot",
                        "Emperador Vainilla",
                        "Fritos Limon Y Sal",
                        "Nissin Dark Dragon",
                        "Agua Natural 600 Ml",
                        "Emperador Chocolate",
                        "Mega Cuerno Clasico",
                        "Sabritas Flamin Hot",
                        "Sabritas Originales",
                        "Leche De Chocolate Sc",
                        "Cuerno Clasico De Pavo",
                        "Topochico Seltzer Mango",
                        "Combo Snack Con Frubotana",
                        "Vino Tinto Sangre De Toro",
                        "Taxi Zihuatanejo Zona 2 - 3pax",
                        "Taxi Cdmx- Interlomas_Bosque-Real",
                        "Taxi Huatulco Mazunte/Zipolite 3pax")

# Verificar que los valores corregidos estén bien
print("Valores corregidos para ProductName:")
print(valores_corregidos)
```

### Columna Type (Servicio - Fisico)
```{r}
# Definir una función para asignar el tipo según el tipo de producto
asignar_tipo <- function(producto_tipo) {
  if (producto_tipo %in% c("Vivabus", "Transportaciones CUN", "Transportaciones MTY", 
                           "Transportaciones TLC", "Viva Play", "Viva Taxis", 
                           "Viva Transfer", "Antros")) {
    return("Servicio")
  } else {
    return("Fisico")
  }
}

# Aplicar la función a la columna ProductType para crear la nueva columna Type
ventas$Type <- sapply(ventas$ProductType, asignar_tipo)

# Verificar que se haya creado correctamente la nueva columna
head(ventas)
```

### Partición Type Fisico
```{r message=FALSE, warning=FALSE}
# Función para asignar el subtipo según el tipo de producto
asignar_subtipo <- function(producto_tipo, tipo) {
  if (tipo == "Servicio") {
    if (producto_tipo %in% c("Viva Transfer", "Viva Taxis", 
                             "Transportaciones MTY", "Transportaciones CUN", "Vivabus")) {
      return("Transporte")
    } else if (producto_tipo %in% c("Antros")) {
      return("Entretenimiento")
    } else if (producto_tipo %in% c("Viva Play")) {
      return("Online")
    } else {
      return("Otros Servicios")
    }
  } else {
    if (producto_tipo %in% c("Perecederos", "Alimentos Charter")) {
      return("Perecederos")
    } else {
      return("No Perecederos")
    }
  }
}

# Aplicar la función a las columnas ProductType y Type para crear la nueva columna SubType
ventas$SubType <- mapply(asignar_subtipo, ventas$ProductType, ventas$Type)

# Verificar que se haya creado correctamente la nueva columna
head(ventas)
```

### Join 
```{r}
df <- vuelos_alt %>% 
  left_join(ventas, by = "Flight_ID")
```


## Correciones base
```{r}
df_alt <- df %>%
  filter(Type != "Servicios") %>%
  filter(ProductType!= "Specials")%>%
  filter(STD_Año != 2024)%>%
  filter(ProductType != "Combos Crew")%>%
  filter(ProductType != "Ofertas")%>%
  filter(diferencia_horas < 15)%>%
  filter(DepartureStation != "")%>%
  filter(ArrivalStation != "")%>%
  filter(Origin_Type != "")%>%
  filter(Destination_Type != "")
```

```{r}
df_alt <- df_alt %>%
  dplyr::select(-Aeronave, -TotalSales)
```

```{r}
df_alt$ruta <- paste(df_alt$DepartureStation, df_alt$ArrivalStation)
```

```{r}
df_2 <- subset(df_alt, select = -STD)
df_2 <- subset(df_2, select = -STA)
df_2 <- subset(df_2, select = -Flight_ID)
df_2 <- subset(df_2, select = -STD_Dia_del_mes)
df_2 <- subset(df_2, select = -STD_Año)
df_2 <- subset(df_2, select = -STD_Mes)
df_2 <- subset(df_2, select = -STA_Dia_del_mes)
df_2 <- subset(df_2, select = -STA_Año)
df_2 <- subset(df_2, select = -STA_Mes)
df_2 <- subset(df_2, select = -Porcentaje_Reservas)
df_2 <- subset(df_2, select = -ProductType)
df_2 <- subset(df_2, select = -Type)
df_2 <- subset(df_2, select = -SubType)
df_2 <- subset(df_2, select = -DepartureStation)
df_2 <- subset(df_2, select = -ArrivalStation)
df_2 <- subset(df_2, select = -Passengers)
df_2 <- subset(df_2, select = -Bookings)
df_2 <- subset(df_2, select = -diferencia_minutos)
```

```{r}
df_2$Capacity <- ifelse(df_2$Capacity > 230, "Grande",
                              ifelse(df_2$Capacity >= 200 & df_2$Capacity <= 230, "Mediano", "Pequeño"))

df_2$diferencia_horas <- ifelse(df_2$diferencia_horas > 3, "Largo",
                              ifelse(df_2$diferencia_horas >= 2 & df_2$diferencia_horas <= 3, "Medio", "Corto"))

df_2$Porcentaje_Capacidad <- ifelse(df_2$Porcentaje_Capacidad > 80, "Poco espacio a lleno",
                              ifelse(df_2$Porcentaje_Capacidad >= 50 & df_2$Porcentaje_Capacidad <= 80, "Moderadamente lleno", "Mitad o menos"))

df_2$Capacity <- ifelse(df_2$Capacity > 230, "Grande",
                              ifelse(df_2$Capacity >= 200 & df_2$Capacity <= 230, "Mediano", "Pequeño"))

df_2$STD_hora <- substr(df_2$STD_hora, 1, 2)

df_2$STD_hora <- ifelse(as.numeric(df_2$STD_hora) >= 0 & as.numeric(df_2$STD_hora) < 6, "Madrugada a mañana",
                            ifelse(as.numeric(df_2$STD_hora) >= 6 & as.numeric(df_2$STD_hora) < 18, "Tarde", "Noche"))

df_2$STA_hora <- substr(df_2$STA_hora, 1, 2)

df_2$STA_hora <- ifelse(as.numeric(df_2$STA_hora) >= 0 & as.numeric(df_2$STA_hora) < 6, "Madrugada a mañana",
                            ifelse(as.numeric(df_2$STA_hora) >= 6 & as.numeric(df_2$STA_hora) < 18, "Tarde", "Noche"))

colnames(df_2)[colnames(df_2) == "diferencia_horas"] <- "Longitud_viaje"
```

